version : '3.7'

# 컴퓨터들
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  database:
    image: mongo:5
    ports:
      - 27017:27017


# 1. 빌드하기
# docker-compose build

# 2. 실행하기
# docker-compose up

# 3. 도커 컴 접속하기
# docker exec -it 컨테이너ID /bin/bash
# mongo 몽고쉘 접속
# show databases
# use local
# show collections
# exit